import Vue from "vue";

export default {
  state: {
    fields: {
      client_name: "",
      job_id: "",
      print_id: "",
      record_id: "",
      limit: "",
      field_name: ""
    },
    sqlFieldInputs: [
      {
        field_name: "client_name", //this has to match the key names in state.fields
        placeholder: "Client Name", //this is the field's placeholder value
        icon: "user-tie", //make sure this icon is registered locally in your vue file
        number: false
      },
      {
        field_name: "job_id",
        placeholder: "Job ID",
        icon: "briefcase",
        number: true
      },
      {
        field_name: "print_id",
        placeholder: "Print ID",
        icon: "print",
        number: true
      },
      {
        field_name: "record_id",
        placeholder: "Record ID",
        icon: "compact-disc",
        number: true
      },
      {
        field_name: "limit",
        placeholder: "Limit",
        icon: "hand-paper",
        number: true
      },
      {
        field_name: "field_name",
        placeholder: "Field Name",
        icon: "stream",
        number: false
      }
    ],
    client_list: [
      "disclose",
      "adoption",
      "extraterrestrial",
      "edge",
      "mud",
      "violation",
      "shift",
      "note",
      "navy",
      "education",
      "sculpture",
      "negative",
      "jump",
      "daughter",
      "risk",
      "fence",
      "locate",
      "qualify",
      "mayor",
      "host",
      "can",
      "criticism",
      "shadow",
      "legend",
      "linear",
      "emphasis",
      "swell",
      "helmet",
      "scale",
      "wheel",
      "slam",
      "manufacturer",
      "junior",
      "design",
      "retiree",
      "rob",
      "pure",
      "translate",
      "pluck",
      "lot",
      "human body",
      "enlarge",
      "obese",
      "kidney",
      "feed",
      "bridge",
      "code",
      "pawn",
      "funny",
      "soul",
      "cafe",
      "text",
      "cattle",
      "old age",
      "raw",
      "credibility",
      "gate",
      "carry",
      "reconcile",
      "revive",
      "pour",
      "Mars",
      "contract",
      "colleague",
      "crown",
      "transmission",
      "message",
      "branch",
      "expand",
      "nursery",
      "depart",
      "species",
      "struggle",
      "attraction",
      "peanut",
      "pace",
      "lonely",
      "exploration",
      "heal",
      "oil",
      "conventional",
      "goal",
      "spy",
      "forecast",
      "chew",
      "theorist",
      "indication",
      "dragon",
      "thumb",
      "monopoly",
      "staircase",
      "robot",
      "impact",
      "good",
      "eat",
      "enhance",
      "syndrome",
      "copy",
      "posture",
      "epicalyx",
      "price",
      "brink",
      "diplomatic",
      "joint",
      "confession",
      "law",
      "skin",
      "park",
      "elapse",
      "sweat",
      "bubble",
      "chop",
      "workshop",
      "repeat",
      "trace",
      "cigarette",
      "patent",
      "national",
      "skeleton",
      "adult",
      "wedding",
      "discourage",
      "studio",
      "obscure",
      "cunning",
      "stun",
      "take",
      "aquarium",
      "cinema",
      "river",
      "consultation",
      "lifestyle",
      "tired",
      "personal",
      "appetite",
      "insurance",
      "vain",
      "particle",
      "relative",
      "flatware",
      "demonstrator",
      "prosper",
      "estimate",
      "bold",
      "bend",
      "ridge",
      "accent",
      "know",
      "context",
      "lunch",
      "lie",
      "avant-garde",
      "clarify",
      "journal",
      "view",
      "sympathetic",
      "fossil",
      "bush",
      "dribble",
      "catalogue",
      "scheme",
      "picture",
      "reinforce",
      "lion",
      "assessment",
      "pledge",
      "provincial",
      "convert",
      "guess",
      "brave",
      "candidate",
      "threaten",
      "cord",
      "organ",
      "settle",
      "defeat",
      "fairy",
      "prosecution",
      "scrape",
      "modernize",
      "factory",
      "honest",
      "sketch",
      "drag",
      "hike",
      "liability",
      "urine",
      "punish",
      "census",
      "decorative",
      "combination",
      "escape",
      "ant",
      "thanks",
      "rebellion",
      "definition",
      "stretch",
      "maze",
      "mainstream",
      "bathroom",
      "eyebrow",
      "elect",
      "attic",
      "explosion",
      "primary",
      "ambiguity",
      "brilliance",
      "assembly",
      "leg",
      "continuation",
      "password",
      "multimedia",
      "overview",
      "rescue",
      "dialogue",
      "overcharge",
      "motivation",
      "account",
      "deteriorate",
      "forbid",
      "accurate",
      "prefer",
      "bundle",
      "shark",
      "opposition",
      "fund",
      "hell",
      "equip",
      "gutter",
      "play",
      "sum",
      "fuel",
      "bill",
      "arm",
      "cover",
      "warrant",
      "coach",
      "incapable",
      "pocket",
      "essay",
      "dish",
      "garage",
      "strikebreaker",
      "improve",
      "classroom",
      "timber",
      "shelf",
      "bake",
      "strike",
      "sick",
      "gesture",
      "battlefield",
      "assignment",
      "extort",
      "share",
      "stomach",
      "concession",
      "halt",
      "influence",
      "flow",
      "noble",
      "defendant",
      "pole",
      "end",
      "prove",
      "principle",
      "slant",
      "diet",
      "resign",
      "study",
      "braid",
      "assault",
      "safety",
      "ready",
      "paragraph",
      "flesh",
      "haunt",
      "skip",
      "intermediate",
      "shower",
      "activity",
      "verdict",
      "damn",
      "bring",
      "brainstorm",
      "abstract",
      "premature",
      "rice",
      "distribute",
      "concede",
      "index",
      "dimension",
      "frank",
      "technique",
      "fluctuation",
      "blast",
      "player",
      "storm",
      "bathtub",
      "project"
    ]
  },
  getters: {
    sqlFieldInputs: state => state.sqlFieldInputs,
    getSQLFields: state => state.fields,
    getClientList: state => state.client_list
  },
  mutations: {
    editSQLField(state, { field_name, data }) {
      var check = state.sqlFieldInputs.filter(function(el) {
        return el.number && el.field_name === field_name;
      });

      if (check.length === 1) {
        data = data.replace(/\D/g, "");
      }
      Vue.set(state.fields, field_name, data.trim());
    },
    clearSQLField(state, field_name) {
      Vue.set(state.fields, field_name, "");
    }
  },
  actions: {
    checkNum: ({ commit }, event) => commit("checkNum", event),
    editSQLField: ({ commit }, payload) => commit("editSQLField", payload),
    clearSQLField: ({ commit }, field_name) =>
      commit("clearSQLField", field_name)
  }
};
